apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: how-is-my-stock-doing
  annotations:
    github.com/project-slug: paulmorar/how-is-my-stock-doing
spec:
  type: other
  lifecycle: unknown
  owner: guests
